#!/usr/bin/env python3
import logging
import pprint
import pyaudio

log = logging.getLogger(__name__)

def print_audio_devices(pa):
    for ii in range(pa.get_device_count()):
        d = pa.get_device_info_by_index(ii)
        pprint.pprint(d)

logging.basicConfig(level=logging.DEBUG)
pa = pyaudio.PyAudio()
print_audio_devices(pa)

